### PR TITLE
Updating to Julia v1.1

### PR DESCRIPTION
**Pull request by kraftpunk97-zz**
ArcadeLearningEnvironment.jl has not seen updates since Julia v0.6. The objective of this PR is to update this package and make it functional again.

### CODE REVIEW

**Comment by kraftpunk97** [comment]
@nowozin When running the build.jl script, the installer created a `deps` folder outside of the `ArcadeLearningEnvironment.jl` package directory. Is that to be expected?

**Comment by nowozin** [comment]
Thanks!

**Comment by nowozin** [comment]
You closed the PR; do you want me to merge your PR?

**Comment by kraftpunk97-zz** [comment]
@nowozin Oh, I saw that you weren't active on GitHub and I thought that I wouldn't get feedback regarding the PR, so I closed it. Sorry for that. Definitely interested in getting these changes pushed. However, I will need some time (2-3 days). I will reopen the PR as a draft, if that's okay?

**Comment by kraftpunk97-zz** [comment]
Just running a few changes. Basically updating to ALE v0.6.0 and if we could register it to the official Julia package registry, that would be super.

**Comment by nowozin** [comment]
Ok, let me know when it is ready to merge.  Also, I am happy to pass the torch if you want to become maintainer of this repository.

**Comment by kraftpunk97-zz** [comment]
If you're sure about it, I'll be happy to take it off your hands after the
PR has been merged.

**Comment by kraftpunk97-zz** [comment]
@nowozin the PR is ready is for review. I can really use your help with one small issue. I don't know if this was because I was working in `dev` mode, but when I run the build script, I get a directory structure like this...

```
dev/
├── ArcadeLearningEnvironment/
│   ├── deps/
│   ├── src/
│   ├── test/
│   ├── appveyor.yml
│   ├── LICENSE.md
│   ├── REQUIRE
│   └── README.md
└── deps/
    ├── src/
    └── usr/
```
There are two `deps` folder, one in the `dev` folder and the other in the `ArcadeLearningEnvironment` folder. The first directory was created when the build script was run. I'm guessing that shouldn't be the case. the `usr/` and `src/` folders in the `dev/-->deps/` folder should be in `dev/-->ArcadeLearningEnvironment/-->deps/` folder. Is it possible to tweak the build script to make it so?

**Comment by kraftpunk97-zz** [comment]
pinging @nowozin

**Pull request closed without merging**
